#!/bin/bash

ARR=()
ARR+=("Power")
ARR+=("  Restart")
ARR+=("  Shut Down")

CHOICE=$(printf '%s\n' "${ARR[@]}" | rofi -dmenu -p "Menu")

if [ "$CHOICE" = "Restart" ]; then
    sudo reboot
    exit 0
fi

if [ "$CHOICE" = "Shut Down" ]; then
    sudo poweroff
    exit 0
fi
